"""Generate dependency-free C/Rust constants and wire tables; --check forbids drift."""
import argparse
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]


def render():
    spec = json.loads((ROOT / 'contract/wire.json').read_text())
    values = dict(spec['constants'])
    tables = ['# Generated wire layout tables', '',
              'Source: [`contract/wire.json`](../contract/wire.json). Do not edit this file.',
              'See [normative semantics](wire-format.md). Offsets are bytes, little-endian.', '']
    widths = {'u8': 1, 'u16': 2, 'u32': 4, 'i32': 4, 'u64': 8}
    for name, fields in spec['layouts'].items():
        offset = 0
        tables += [f'## {name}', '', '| Field | Offset | Type / bytes |', '| --- | --- | --- |']
        for field, kind in fields:
            width = widths[kind] if kind in widths else int(kind)
            assert width > 0
            key = f'{name}_{field}_offset'.upper()
            assert key not in values
            values[key] = offset
            tables += [f'| {field} | {offset} | {kind} |']
            offset += width
        values[name.upper() + '_BYTES'] = offset
        tables += ['', f'Fixed size: {offset} bytes.', '']
    assert values['PACKAGE_BYTES'] == 80 and values['TAG_BYTES'] == 40
    assert values['INFO_RESPONSE_BYTES'] <= 256
    assert values['READ_TAGS_RESPONSE_BYTES'] + values['TAG_PAGE_LIMIT'] * values['TAG_VALUE_BYTES'] <= 256
    tables += ['## Numeric constants', '', '| Name | Value |', '| --- | --- |']
    tables += [f'| {name} | {value} |' for name, value in spec['constants'].items()]
    tables += ['']
    c = ['/* Generated by scripts/generate_wire.py from contract/wire.json. */',
         '#ifndef TINYPLC_WIRE_GENERATED_H', '#define TINYPLC_WIRE_GENERATED_H', '#include <stdint.h>']
    rust = ['// Generated by scripts/generate_wire.py from contract/wire.json.']
    for name, value in values.items():
        assert name.replace('_', '').isalnum() and name == name.upper()
        assert isinstance(value, int) and 0 <= value <= 0xffffffff
        c += [f'#define TPLC_{name} UINT32_C({value})']
        rust += [f'pub const {name}: u32 = {value};']
    c += ['#endif', '']
    return {ROOT / 'contract/wire_generated.h': '\n'.join(c),
            ROOT / 'contract/src/generated.rs': '\n'.join(rust) + '\n',
            ROOT / 'docs/wire-layouts.md': '\n'.join(tables)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, contents in render().items():
        if args.check:
            if not path.exists() or path.read_text() != contents:
                raise SystemExit(f'Stale generated file: {path.relative_to(ROOT)}; run scripts/generate_wire.py')
        else:
            path.write_text(contents)


if __name__ == '__main__':
    main()
